version: '3.4'



####### Networks #######

networks:
  networkPortal:

####### Services #######
services:

#-----------------------------------------------------------------------
  shj.abp.commerce.httpapi.host:
    container_name: "ShjCommerceApi"
    image: ${DOCKER_REGISTRY-}shjabpcommercehttpapihost
    build:
      context: .
      dockerfile: src/SHJ.ABP.Commerce.HttpApi.Host/Dockerfile
#-----------------------------------------------------------------------
  MsSqLServer2019:
    container_name: MsSqLServer2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Aa@123456
      - ACCEPT_EULA=Y
    ports:
      - 44332:44432
    networks:
     - networkPortal
#-----------------------------------------------------------------------
